///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package Java.Fundamentals.Inheritance;
//
//public class App {
//
//
//    public static void main(String[] args) {
//        Restraunt rest = new Restraunt("Pickle Ricks Fried Pickles",5,4);;

//        System.out.println(rest.getName());
//        System.out.println(rest.getStars());
//        System.out.println(rest.getPriceCat());
//        String stuff = "wit is very good";
//        System.out.println(rest.addRev(stuff));
//        System.out.println(rest);
//        rest.toString();


//        Review rev = new Review("Jim","was a very BEETY time ",5);
//        System.out.println(rev);
//        rev.toString();
//        System.out.println( rev.getName());
//        System.out.println(rev.getStars());
//        System.out.println(rev.getBody());

//
//
//
//    }
//}
